Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus\browser_decorator.py", line 201, in run_task
    result = func(driver, data)
  File "c:\Users\Admin\Downloads\Code\OOPFinalProject\Project\utils\cloudflare_bypass.py", line 42, in get_bypassed_page_source
    driver.google_get(url, bypass_cloudflare=True)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 2230, in google_get
    self.get_via(
    ~~~~~~~~~~~~^
        link,
        ^^^^^
    ...<4 lines>...
        timeout=timeout,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 2204, in get_via
    self.detect_and_bypass_cloudflare()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 1397, in detect_and_bypass_cloudflare
    bypass_if_detected(self)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 273, in bypass_if_detected
    solve_full_cf(driver)
    ~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 161, in solve_full_cf
    wait_till_cloudflare_leaves(driver, previous_ray_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 118, in wait_till_cloudflare_leaves
    raise CloudflareDetectionException()
botasaurus_driver.exceptions.CloudflareDetectionException: Cloudflare has detected us.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus\browser_decorator.py", line 201, in run_task
    result = func(driver, data)
  File "c:\Users\Admin\Downloads\Code\OOPFinalProject\Project\utils\cloudflare_bypass.py", line 42, in get_bypassed_page_source
    driver.google_get(url, bypass_cloudflare=True)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 2230, in google_get
    self.get_via(
    ~~~~~~~~~~~~^
        link,
        ^^^^^
    ...<4 lines>...
        timeout=timeout,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 2204, in get_via
    self.detect_and_bypass_cloudflare()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 1397, in detect_and_bypass_cloudflare
    bypass_if_detected(self)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 273, in bypass_if_detected
    solve_full_cf(driver)
    ~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 161, in solve_full_cf
    wait_till_cloudflare_leaves(driver, previous_ray_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 118, in wait_till_cloudflare_leaves
    raise CloudflareDetectionException()
botasaurus_driver.exceptions.CloudflareDetectionException: Cloudflare has detected us.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus\browser_decorator.py", line 201, in run_task
    result = func(driver, data)
  File "c:\Users\Admin\Downloads\Code\OOPFinalProject\Project\utils\cloudflare_bypass.py", line 42, in get_bypassed_page_source
    driver.google_get(url, bypass_cloudflare=True)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 2230, in google_get
    self.get_via(
    ~~~~~~~~~~~~^
        link,
        ^^^^^
    ...<4 lines>...
        timeout=timeout,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 2204, in get_via
    self.detect_and_bypass_cloudflare()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 1397, in detect_and_bypass_cloudflare
    bypass_if_detected(self)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 273, in bypass_if_detected
    solve_full_cf(driver)
    ~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 161, in solve_full_cf
    wait_till_cloudflare_leaves(driver, previous_ray_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 118, in wait_till_cloudflare_leaves
    raise CloudflareDetectionException()
botasaurus_driver.exceptions.CloudflareDetectionException: Cloudflare has detected us.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus\browser_decorator.py", line 201, in run_task
    result = func(driver, data)
  File "c:\Users\Admin\Downloads\Code\OOPFinalProject\Project\utils\cloudflare_bypass.py", line 42, in get_bypassed_page_source
    driver.google_get(url, bypass_cloudflare=True)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 2230, in google_get
    self.get_via(
    ~~~~~~~~~~~~^
        link,
        ^^^^^
    ...<4 lines>...
        timeout=timeout,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 2204, in get_via
    self.detect_and_bypass_cloudflare()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 1397, in detect_and_bypass_cloudflare
    bypass_if_detected(self)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 273, in bypass_if_detected
    solve_full_cf(driver)
    ~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 161, in solve_full_cf
    wait_till_cloudflare_leaves(driver, previous_ray_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 118, in wait_till_cloudflare_leaves
    raise CloudflareDetectionException()
botasaurus_driver.exceptions.CloudflareDetectionException: Cloudflare has detected us.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus\browser_decorator.py", line 201, in run_task
    result = func(driver, data)
  File "c:\Users\Admin\Downloads\Code\OOPFinalProject\Project\utils\cloudflare_bypass.py", line 42, in get_bypassed_page_source
    driver.google_get(url, bypass_cloudflare=True)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 2230, in google_get
    self.get_via(
    ~~~~~~~~~~~~^
        link,
        ^^^^^
    ...<4 lines>...
        timeout=timeout,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 2204, in get_via
    self.detect_and_bypass_cloudflare()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 1397, in detect_and_bypass_cloudflare
    bypass_if_detected(self)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 273, in bypass_if_detected
    solve_full_cf(driver)
    ~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 161, in solve_full_cf
    wait_till_cloudflare_leaves(driver, previous_ray_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 118, in wait_till_cloudflare_leaves
    raise CloudflareDetectionException()
botasaurus_driver.exceptions.CloudflareDetectionException: Cloudflare has detected us.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus\browser_decorator.py", line 201, in run_task
    result = func(driver, data)
  File "c:\Users\Admin\Downloads\Code\OOPFinalProject\Project\utils\cloudflare_bypass.py", line 42, in get_bypassed_page_source
    driver.google_get(url, bypass_cloudflare=True)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 2230, in google_get
    self.get_via(
    ~~~~~~~~~~~~^
        link,
        ^^^^^
    ...<4 lines>...
        timeout=timeout,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 2204, in get_via
    self.detect_and_bypass_cloudflare()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\driver.py", line 1397, in detect_and_bypass_cloudflare
    bypass_if_detected(self)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 273, in bypass_if_detected
    solve_full_cf(driver)
    ~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 161, in solve_full_cf
    wait_till_cloudflare_leaves(driver, previous_ray_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\Code\OOPFinalProject\Project\.venv\Lib\site-packages\botasaurus_driver\solve_cloudflare_captcha.py", line 118, in wait_till_cloudflare_leaves
    raise CloudflareDetectionException()
botasaurus_driver.exceptions.CloudflareDetectionException: Cloudflare has detected us.
